language: python

python:

  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.4"

install:
# install packages
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database ah_alpha_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
# running tests
  - coverage run --source=authors/apps manage.py test
  - coverage report

after_success:
# send coverage to coveralls
  - coveralls
